name: unpivoter
description: A simple command-line application.
version: 1.0.0
homepage: http://mikefenwick.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  args: ^2.3.0
  grizzly_io: ^3.0.1


dev_dependencies:
  lints: ^1.0.0
